# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statisticsTable.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_statisticsTable(object):
    def setupUi(self, statisticsTable):
        statisticsTable.setObjectName("statisticsTable")
        statisticsTable.resize(889, 599)
        self.verticalLayout = QtWidgets.QVBoxLayout(statisticsTable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetContainer = QtWidgets.QTabWidget(statisticsTable)
        self.tabWidgetContainer.setObjectName("tabWidgetContainer")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableByNode = QtWidgets.QTableWidget(self.tab)
        self.tableByNode.setObjectName("tableByNode")
        self.tableByNode.setColumnCount(4)
        self.tableByNode.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableByNode.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByNode.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByNode.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByNode.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tableByNode)
        self.tabWidgetContainer.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableByDate = QtWidgets.QTableWidget(self.tab_2)
        self.tableByDate.setObjectName("tableByDate")
        self.tableByDate.setColumnCount(4)
        self.tableByDate.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableByDate.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByDate.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByDate.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByDate.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableByDate)
        self.tabWidgetContainer.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableByPosition = QtWidgets.QTableWidget(self.tab_3)
        self.tableByPosition.setObjectName("tableByPosition")
        self.tableByPosition.setColumnCount(4)
        self.tableByPosition.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableByPosition.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByPosition.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByPosition.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByPosition.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_2.addWidget(self.tableByPosition)
        self.tabWidgetContainer.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableByTime = QtWidgets.QTableWidget(self.tab_4)
        self.tableByTime.setRowCount(2)
        self.tableByTime.setColumnCount(8)
        self.tableByTime.setObjectName("tableByTime")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableByTime.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableByTime.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableByTime.setItem(1, 7, item)
        self.tableByTime.horizontalHeader().setVisible(False)
        self.tableByTime.horizontalHeader().setCascadingSectionResizes(False)
        self.tableByTime.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableByTime)
        self.tabWidgetContainer.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidgetContainer)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnSave = QtWidgets.QPushButton(statisticsTable)
        self.btnSave.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_3.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(statisticsTable)
        self.btnCancel.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(statisticsTable)
        self.tabWidgetContainer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(statisticsTable)

    def retranslateUi(self, statisticsTable):
        _translate = QtCore.QCoreApplication.translate
        statisticsTable.setWindowTitle(_translate("statisticsTable", "Dialog"))
        item = self.tableByNode.horizontalHeaderItem(0)
        item.setText(_translate("statisticsTable", "节点名"))
        item = self.tableByNode.horizontalHeaderItem(1)
        item.setText(_translate("statisticsTable", "节点数"))
        item = self.tableByNode.horizontalHeaderItem(2)
        item.setText(_translate("statisticsTable", "错误数"))
        item = self.tableByNode.horizontalHeaderItem(3)
        item.setText(_translate("statisticsTable", "准确率"))
        self.tabWidgetContainer.setTabText(self.tabWidgetContainer.indexOf(self.tab), _translate("statisticsTable", "按照节点统计"))
        item = self.tableByDate.horizontalHeaderItem(0)
        item.setText(_translate("statisticsTable", "日期"))
        item = self.tableByDate.horizontalHeaderItem(1)
        item.setText(_translate("statisticsTable", "节点数"))
        item = self.tableByDate.horizontalHeaderItem(2)
        item.setText(_translate("statisticsTable", "错误数"))
        item = self.tableByDate.horizontalHeaderItem(3)
        item.setText(_translate("statisticsTable", "准确率"))
        self.tabWidgetContainer.setTabText(self.tabWidgetContainer.indexOf(self.tab_2), _translate("statisticsTable", "按天统计"))
        item = self.tableByPosition.horizontalHeaderItem(0)
        item.setText(_translate("statisticsTable", "机位"))
        item = self.tableByPosition.horizontalHeaderItem(1)
        item.setText(_translate("statisticsTable", "节点数"))
        item = self.tableByPosition.horizontalHeaderItem(2)
        item.setText(_translate("statisticsTable", "错误数"))
        item = self.tableByPosition.horizontalHeaderItem(3)
        item.setText(_translate("statisticsTable", "准确率"))
        self.tabWidgetContainer.setTabText(self.tabWidgetContainer.indexOf(self.tab_3), _translate("statisticsTable", "按机位统计"))
        __sortingEnabled = self.tableByTime.isSortingEnabled()
        self.tableByTime.setSortingEnabled(False)
        item = self.tableByTime.item(0, 0)
        item.setText(_translate("statisticsTable", "白天"))
        item = self.tableByTime.item(0, 4)
        item.setText(_translate("statisticsTable", "晚上"))
        item = self.tableByTime.item(1, 0)
        item.setText(_translate("statisticsTable", "节点名"))
        item = self.tableByTime.item(1, 1)
        item.setText(_translate("statisticsTable", "节点数"))
        item = self.tableByTime.item(1, 2)
        item.setText(_translate("statisticsTable", "错误数"))
        item = self.tableByTime.item(1, 3)
        item.setText(_translate("statisticsTable", "准确率"))
        item = self.tableByTime.item(1, 4)
        item.setText(_translate("statisticsTable", "节点名"))
        item = self.tableByTime.item(1, 5)
        item.setText(_translate("statisticsTable", "节点数"))
        item = self.tableByTime.item(1, 6)
        item.setText(_translate("statisticsTable", "错误数"))
        item = self.tableByTime.item(1, 7)
        item.setText(_translate("statisticsTable", "准确率"))
        self.tableByTime.setSortingEnabled(__sortingEnabled)
        self.tabWidgetContainer.setTabText(self.tabWidgetContainer.indexOf(self.tab_4), _translate("statisticsTable", "按昼夜统计"))
        self.btnSave.setText(_translate("statisticsTable", "保存"))
        self.btnCancel.setText(_translate("statisticsTable", "取消"))

