# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 333)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setStyleSheet("QWidget#Login\n"
"{\n"
"    height: 400px;\n"
"    widght: 300px;\n"
"    background:#182B51;\n"
"}\n"
"\n"
"QPushButton#pushButton_login\n"
"{\n"
"    border-radius:5px;\n"
"    max-width:100px;\n"
"    min-width:100px;\n"
"    max-height:25px;\n"
"    font-family: 微软雅黑;\n"
"    font-size: 16px;\n"
"    color: #FFFFFF;\n"
"    background-color:#42A1ED;\n"
"}\n"
"\n"
"QPushButton:pressed#pushButton_login\n"
"{\n"
"    background-color: light gray;\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"QLabel#label_name\n"
"{\n"
"    text-align: center;\n"
"    max-width:45px;\n"
"    min-height:20px;\n"
"    max-height:15px;\n"
"    font-family: 微软雅黑;\n"
"    font-size: 14px;\n"
"    color: #B9DAFF;\n"
"}\n"
"\n"
"QLabel#label_password\n"
"{\n"
"    text-align: center;\n"
"    max-width:45px;\n"
"    min-height:20px;\n"
"    max-height:15px;\n"
"    font-family: 微软雅黑;\n"
"    font-size: 14px;\n"
"    color: #B9DAFF;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_img = QtWidgets.QLabel(self.widget)
        self.label_img.setMaximumSize(QtCore.QSize(150, 150))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("C:/Users/feeyo/Pictures/用户管理.png"))
        self.label_img.setScaledContents(True)
        self.label_img.setObjectName("label_img")
        self.horizontalLayout_2.addWidget(self.label_img)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Login)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_name = QtWidgets.QLabel(self.widget_2)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_name.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_password = QtWidgets.QLabel(self.widget_2)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_password.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Login)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_login = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout.addWidget(self.pushButton_login)
        spacerItem1 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_3)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label_name.setText(_translate("Login", "用户名："))
        self.label_password.setText(_translate("Login", "密  码："))
        self.pushButton_login.setText(_translate("Login", "登录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
